name: SonarCloud Analysis

on:
  push:
    branches:
      - main
    paths:
        - 'RPAs/FaturaPdfCatolica/**'
        - 'RPAs/HistoricoFipe/**'
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Convert shallow clone to full clone
        run: git fetch --unshallow

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Tools
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Analyze FaturaPdfCatolica
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd RPAs/FaturaPdfCatolica
          dotnet-sonarscanner begin /k:"rpasboettscher_faturapdfcatolica" /o:"rpasboettscher" /d:sonar.branch.name="main" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet restore FaturaPdfCatolica.sln
          dotnet build FaturaPdfCatolica.sln
          dotnet test FaturaPdfCatolica.sln --logger "trx" --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=opencover /p:CoverletOutput=TestResults/coverage.opencover.xml
          reportgenerator -reports:TestResults/coverage.opencover.xml -targetdir:TestResults/CoverageReport -reporttypes:Cobertura
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Analyze HistoricoFipe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd RPAs/HistoricoFipe
          dotnet-sonarscanner begin /k:"rpasboettscher_historicofipe" /o:"rpasboettscher" /d:sonar.branch.name="main" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet restore HistoricoFipe.sln
          dotnet build HistoricoFipe.sln
          dotnet test HistoricoFipe.sln --logger "trx" --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=opencover /p:CoverletOutput=TestResults/coverage.opencover.xml
          reportgenerator -reports:TestResults/coverage.opencover.xml -targetdir:TestResults/CoverageReport -reporttypes:Cobertura
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
