name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x

      - name: Install SonarCloud Scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Analyze FaturaPdfCatolica
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          $branchName = "${{ github.head_ref || 'main' }}"
          $pullRequestKey = "${{ github.event.pull_request.number || '' }}"
          $pullRequestBranch = "${{ github.head_ref || '' }}"
          $pullRequestBase = "${{ github.base_ref || '' }}"

          $sonarParams = "/k:`"rpasboettscher_faturapdfcatolica`" /o:`"rpasboettscher`" /d:sonar.branch.name=`"$branchName`" /d:sonar.token=`"$env:SONAR_TOKEN`" /d:sonar.host.url=`"https://sonarcloud.io`""

          if (![string]::IsNullOrEmpty($pullRequestKey) -and `
              ![string]::IsNullOrEmpty($pullRequestBranch) -and `
              ![string]::IsNullOrEmpty($pullRequestBase)) {
              $sonarParams += " /d:sonar.pullrequest.key=`"$pullRequestKey`""
              $sonarParams += " /d:sonar.pullrequest.branch=`"$pullRequestBranch`""
              $sonarParams += " /d:sonar.pullrequest.base=`"$pullRequestBase`""
          }

          dotnet-sonarscanner begin $sonarParams
          dotnet build RPAs/FaturaPdfCatolica/FaturaPdfCatolica.sln
          dotnet-sonarscanner end /d:sonar.token="$env:SONAR_TOKEN"

      - name: Analyze HistoricoFipe
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          $branchName = "${{ github.head_ref || 'main' }}"
          $pullRequestKey = "${{ github.event.pull_request.number || '' }}"
          $pullRequestBranch = "${{ github.head_ref || '' }}"
          $pullRequestBase = "${{ github.base_ref || '' }}"

          $sonarParams = "/k:`"rpasboettscher_historicofipe`" /o:`"rpasboettscher`" /d:sonar.branch.name=`"$branchName`" /d:sonar.token=`"$env:SONAR_TOKEN`" /d:sonar.host.url=`"https://sonarcloud.io`""

          if (![string]::IsNullOrEmpty($pullRequestKey) -and `
              ![string]::IsNullOrEmpty($pullRequestBranch) -and `
              ![string]::IsNullOrEmpty($pullRequestBase)) {
              $sonarParams += " /d:sonar.pullrequest.key=`"$pullRequestKey`""
              $sonarParams += " /d:sonar.pullrequest.branch=`"$pullRequestBranch`""
              $sonarParams += " /d:sonar.pullrequest.base=`"$pullRequestBase`""
          }

          dotnet-sonarscanner begin $sonarParams
          dotnet build RPAs/HistoricoFipe/HistoricoFipe.sln
          dotnet-sonarscanner end /d:sonar.token="$env:SONAR_TOKEN"
