name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Install dependencies
      run: dotnet restore TesteLambda/TesteLambda/TesteLambda.csproj

    - name: Build project
      run: dotnet build TesteLambda/TesteLambda/TesteLambda.csproj --configuration Release

    - name: Install Lambda Tools
      run: dotnet tool install -g Amazon.Lambda.Tools

    - name: Add Lambda Tools to PATH
      shell: bash
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Change directory to project
      run: cd TesteLambda/TesteLambda

    - name: Package Lambda
      run: dotnet lambda package --configuration Release --output-package ../../package.zip

    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'sa-east-1'
      run: |
        aws lambda update-function-code --function-name my-lambda-function --zip-file fileb://package.zip
