name: Deploy RpaFaturaPdfCatolica to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Builda o projeto
      run: dotnet build FaturaPdfCatolica/FaturaPdfCatolica.sln --configuration Release

    - name: Zipa o arquivo net8.0 para FaturaPdfCatolica.zip
      run: zip -r FaturaPdfCatolica.zip FaturaPdfCatolica/FaturaPdfCatolica/bin/Release/net8.0

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: './FaturaPdfCatolica.zip'
        DEST_DIR: 'RpaPdfCatolicaExec/'  # Diretório de destino no bucket S3
